export const green = "#38C780";
export const red = "#f44336";
export const purple = "#6a1b9a";
export const black = "#000";
export const gray = "#878C93";
export const white = "#FFFFFF";
export const darkpurple = "#4F2A6f";
export const grey = "#EDEDED";
export const transparent = "rgba(0, 0, 0, 0.6)";
