//FAVORITES
export const FAVORITES = "FAVORITES";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";

//HISTORY
export const HISTORY = "HISTORY";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const ADD_TO_HISTORY_CHANGE_DATE = "ADD_TO_HISTORY_CHANGE_DATE";

//SEARCH
export const SEARCH = "SEARCH";
export const ADD_TO_SEARCH = "ADD_TO_SEARCH";
